
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Image image1;

	private global::Gtk.Button button_novi_semestar;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Button button_dodajPredavaca;

	private global::Gtk.Button button_pregledajPredavace;

	private global::Gtk.Button button_dodajUcionicu;

	private global::Gtk.Button button_pregledajUcionicu;

	private global::Gtk.Button button_izlaz;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Button button_pregledRasporeda;

	private global::Gtk.Button button_zauzmiUcionicu;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Izbornik");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("Raspored.Logo_smanjeni.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.BorderWidth = ((uint)(12));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 10;
		this.vbox1.BorderWidth = ((uint)(15));
		// Container child vbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image();
		this.image1.HeightRequest = 238;
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Raspored.vector_sun_book_logo.png");
		this.vbox1.Add(this.image1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.image1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button_novi_semestar = new global::Gtk.Button();
		this.button_novi_semestar.HeightRequest = 40;
		this.button_novi_semestar.CanFocus = true;
		this.button_novi_semestar.Name = "button_novi_semestar";
		this.button_novi_semestar.UseUnderline = true;
		this.button_novi_semestar.Label = global::Mono.Unix.Catalog.GetString("Novi semestar");
		this.vbox1.Add(this.button_novi_semestar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.button_novi_semestar]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.WidthRequest = 192;
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button_dodajPredavaca = new global::Gtk.Button();
		this.button_dodajPredavaca.WidthRequest = 180;
		this.button_dodajPredavaca.HeightRequest = 40;
		this.button_dodajPredavaca.CanFocus = true;
		this.button_dodajPredavaca.Name = "button_dodajPredavaca";
		this.button_dodajPredavaca.UseUnderline = true;
		this.button_dodajPredavaca.Label = global::Mono.Unix.Catalog.GetString("Dodaj predavača");
		this.vbox4.Add(this.button_dodajPredavaca);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button_dodajPredavaca]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button_pregledajPredavace = new global::Gtk.Button();
		this.button_pregledajPredavace.WidthRequest = 180;
		this.button_pregledajPredavace.HeightRequest = 40;
		this.button_pregledajPredavace.CanFocus = true;
		this.button_pregledajPredavace.Name = "button_pregledajPredavace";
		this.button_pregledajPredavace.UseUnderline = true;
		this.button_pregledajPredavace.Label = global::Mono.Unix.Catalog.GetString("Pregledaj predavače");
		this.vbox4.Add(this.button_pregledajPredavace);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button_pregledajPredavace]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		w4.Padding = ((uint)(5));
		// Container child vbox4.Gtk.Box+BoxChild
		this.button_dodajUcionicu = new global::Gtk.Button();
		this.button_dodajUcionicu.WidthRequest = 180;
		this.button_dodajUcionicu.HeightRequest = 40;
		this.button_dodajUcionicu.CanFocus = true;
		this.button_dodajUcionicu.Name = "button_dodajUcionicu";
		this.button_dodajUcionicu.UseUnderline = true;
		this.button_dodajUcionicu.Label = global::Mono.Unix.Catalog.GetString("Dodaj učionicu");
		this.vbox4.Add(this.button_dodajUcionicu);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button_dodajUcionicu]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		w5.Padding = ((uint)(5));
		// Container child vbox4.Gtk.Box+BoxChild
		this.button_pregledajUcionicu = new global::Gtk.Button();
		this.button_pregledajUcionicu.WidthRequest = 180;
		this.button_pregledajUcionicu.HeightRequest = 40;
		this.button_pregledajUcionicu.CanFocus = true;
		this.button_pregledajUcionicu.Name = "button_pregledajUcionicu";
		this.button_pregledajUcionicu.UseUnderline = true;
		this.button_pregledajUcionicu.Label = global::Mono.Unix.Catalog.GetString("Pregledaj učionicu");
		this.vbox4.Add(this.button_pregledajUcionicu);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button_pregledajUcionicu]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		w6.Padding = ((uint)(5));
		this.vbox3.Add(this.vbox4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button_izlaz = new global::Gtk.Button();
		this.button_izlaz.WidthRequest = 180;
		this.button_izlaz.HeightRequest = 40;
		this.button_izlaz.CanFocus = true;
		this.button_izlaz.Name = "button_izlaz";
		this.button_izlaz.UseUnderline = true;
		this.button_izlaz.Label = global::Mono.Unix.Catalog.GetString("Izlaz");
		this.vbox3.Add(this.button_izlaz);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button_izlaz]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		w8.Padding = ((uint)(5));
		this.hbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.WidthRequest = 130;
		this.vbox2.Name = "vbox2";
		this.vbox2.Homogeneous = true;
		this.vbox2.Spacing = 20;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button_pregledRasporeda = new global::Gtk.Button();
		this.button_pregledRasporeda.WidthRequest = 111;
		this.button_pregledRasporeda.HeightRequest = 100;
		this.button_pregledRasporeda.CanFocus = true;
		this.button_pregledRasporeda.Name = "button_pregledRasporeda";
		this.button_pregledRasporeda.UseUnderline = true;
		this.button_pregledRasporeda.Label = global::Mono.Unix.Catalog.GetString("Pregled rasporeda");
		this.vbox2.Add(this.button_pregledRasporeda);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button_pregledRasporeda]));
		w10.Position = 0;
		w10.Padding = ((uint)(5));
		// Container child vbox2.Gtk.Box+BoxChild
		this.button_zauzmiUcionicu = new global::Gtk.Button();
		this.button_zauzmiUcionicu.WidthRequest = 111;
		this.button_zauzmiUcionicu.HeightRequest = 100;
		this.button_zauzmiUcionicu.CanFocus = true;
		this.button_zauzmiUcionicu.Name = "button_zauzmiUcionicu";
		this.button_zauzmiUcionicu.UseUnderline = true;
		this.button_zauzmiUcionicu.Label = global::Mono.Unix.Catalog.GetString("Zauzmi učionicu");
		this.vbox2.Add(this.button_zauzmiUcionicu);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button_zauzmiUcionicu]));
		w11.PackType = ((global::Gtk.PackType)(1));
		w11.Position = 1;
		w11.Padding = ((uint)(5));
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w12.PackType = ((global::Gtk.PackType)(1));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		w12.Padding = ((uint)(15));
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 443;
		this.DefaultHeight = 660;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button_novi_semestar.Clicked += new global::System.EventHandler(this.OnButtonNoviSemestarClicked);
		this.button_dodajPredavaca.Clicked += new global::System.EventHandler(this.OnButtonDodajPredavacaClicked);
		this.button_pregledajPredavace.Clicked += new global::System.EventHandler(this.OnButtonPregledajPredavaceClicked);
		this.button_dodajUcionicu.Clicked += new global::System.EventHandler(this.OnButtonDodajUcionicuClicked);
		this.button_pregledajUcionicu.Clicked += new global::System.EventHandler(this.OnButtonPregledajUcionicuClicked);
		this.button_izlaz.Clicked += new global::System.EventHandler(this.OnButtonIzlazClicked);
		this.button_pregledRasporeda.Clicked += new global::System.EventHandler(this.OnButtonPregledRasporedaClicked);
		this.button_zauzmiUcionicu.Clicked += new global::System.EventHandler(this.OnButtonZauzmiUcionicuClicked);
	}
}
