
// This file has been generated by the GUI designer. Do not modify.
namespace Raspored
{
	public partial class PregledajTermineWindow
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox14;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Label label6;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.ComboBox combobox_ucionice;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Image image_smanjeniLogo;

		private global::Gtk.Label label7;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Button button00_;

		private global::Gtk.Button button01_;

		private global::Gtk.Button button02_;

		private global::Gtk.Button button03_;

		private global::Gtk.Button button04_;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Button button10_;

		private global::Gtk.Button button11_;

		private global::Gtk.Button button12_;

		private global::Gtk.Button button13_;

		private global::Gtk.Button button14_;

		private global::Gtk.HBox hbox19;

		private global::Gtk.Button button20_;

		private global::Gtk.Button button21_;

		private global::Gtk.Button button22_;

		private global::Gtk.Button button23_;

		private global::Gtk.Button button24_;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Button button30_;

		private global::Gtk.Button button31_;

		private global::Gtk.Button button32_;

		private global::Gtk.Button button33_;

		private global::Gtk.Button button34_;

		private global::Gtk.HBox hbox21;

		private global::Gtk.Button button40_;

		private global::Gtk.Button button41_;

		private global::Gtk.Button button42_;

		private global::Gtk.Button button43_;

		private global::Gtk.Button button44_;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Button button50_;

		private global::Gtk.Button button51_;

		private global::Gtk.Button button52_;

		private global::Gtk.Button button53_;

		private global::Gtk.Button button54_;

		private global::Gtk.HBox hbox23;

		private global::Gtk.Button button60_;

		private global::Gtk.Button button61_;

		private global::Gtk.Button button62_;

		private global::Gtk.Button button63_;

		private global::Gtk.Button button64_;

		private global::Gtk.Label label13;

		private global::Gtk.HBox hbox24;

		private global::Gtk.Button button70_;

		private global::Gtk.Button button71_;

		private global::Gtk.Button button72_;

		private global::Gtk.Button button73_;

		private global::Gtk.Button button74_;

		private global::Gtk.HBox hbox25;

		private global::Gtk.Button button80_;

		private global::Gtk.Button button81_;

		private global::Gtk.Button button82_;

		private global::Gtk.Button button83_;

		private global::Gtk.Button button84_;

		private global::Gtk.HBox hbox26;

		private global::Gtk.Button button90_;

		private global::Gtk.Button button91_;

		private global::Gtk.Button button92_;

		private global::Gtk.Button button93_;

		private global::Gtk.Button button94_;

		private global::Gtk.HBox hbox27;

		private global::Gtk.Button button100_;

		private global::Gtk.Button button101_;

		private global::Gtk.Button button102_;

		private global::Gtk.Button button103_;

		private global::Gtk.Button button104_;

		private global::Gtk.HBox hbox28;

		private global::Gtk.Button button110_;

		private global::Gtk.Button button111_;

		private global::Gtk.Button button112_;

		private global::Gtk.Button button113_;

		private global::Gtk.Button button114_;

		private global::Gtk.HBox hbox29;

		private global::Gtk.Button button120_;

		private global::Gtk.Button button121_;

		private global::Gtk.Button button122_;

		private global::Gtk.Button button123_;

		private global::Gtk.Button button124_;

		private global::Gtk.HBox hbox30;

		private global::Gtk.Button button130_;

		private global::Gtk.Button button131_;

		private global::Gtk.Button button132_;

		private global::Gtk.Button button133_;

		private global::Gtk.Button button134_;

		private global::Gtk.HBox hbox31;

		private global::Gtk.Button button140_;

		private global::Gtk.Button button141_;

		private global::Gtk.Button button142_;

		private global::Gtk.Button button143_;

		private global::Gtk.Button button144_;

		private global::Gtk.Frame frame1;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label14;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.HBox hbox32;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Label label15;

		private global::Gtk.Label label16;

		private global::Gtk.Label label17;

		private global::Gtk.Label label18;

		private global::Gtk.Label label19;

		private global::Gtk.Label label20;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Label label_ime;

		private global::Gtk.Label label_prezime;

		private global::Gtk.Label label_OIB;

		private global::Gtk.Label label_opis;

		private global::Gtk.Label label_status;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Fixed fixed5;

		private global::Gtk.Button button1;

		private global::Gtk.Fixed fixed4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Raspored.PregledajTermineWindow
			this.HeightRequest = 650;
			this.Name = "Raspored.PregledajTermineWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Pregledaj termine");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("Raspored.Logo_smanjeni.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Raspored.PregledajTermineWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 8;
			this.hbox14.BorderWidth = ((uint)(20));
			// Container child hbox14.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = -9;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Odaberi učionicu:");
			this.hbox15.Add(this.label6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.label6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(5));
			// Container child hbox15.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox1.Add(this.fixed1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.fixed1]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.combobox_ucionice = global::Gtk.ComboBox.NewText();
			this.combobox_ucionice.WidthRequest = 150;
			this.combobox_ucionice.Name = "combobox_ucionice";
			this.vbox1.Add(this.combobox_ucionice);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.combobox_ucionice]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.vbox1.Add(this.fixed2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.fixed2]));
			w4.Position = 2;
			this.hbox15.Add(this.vbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.vbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(20));
			// Container child hbox15.Gtk.Box+BoxChild
			this.image_smanjeniLogo = new global::Gtk.Image();
			this.image_smanjeniLogo.Name = "image_smanjeniLogo";
			this.image_smanjeniLogo.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Raspored.Logo_smanjeni.png");
			this.hbox15.Add(this.image_smanjeniLogo);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.image_smanjeniLogo]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(34));
			this.vbox5.Add(this.hbox15);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox15]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Prijepodne");
			this.vbox5.Add(this.label7);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label7]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 100;
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Ponedjeljak");
			this.hbox16.Add(this.label8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label8]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.WidthRequest = 100;
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Utorak");
			this.hbox16.Add(this.label9);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label9]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.WidthRequest = 100;
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Srijeda");
			this.hbox16.Add(this.label10);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label10]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.WidthRequest = 100;
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Četvrtak");
			this.hbox16.Add(this.label11);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label11]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.WidthRequest = 100;
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Petak");
			this.hbox16.Add(this.label12);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label12]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox5.Add(this.hbox16);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox16]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button00_ = new global::Gtk.Button();
			this.button00_.WidthRequest = 100;
			this.button00_.CanFocus = true;
			this.button00_.Name = "button00_";
			this.button00_.UseUnderline = true;
			this.button00_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox17.Add(this.button00_);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.button00_]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button01_ = new global::Gtk.Button();
			this.button01_.WidthRequest = 100;
			this.button01_.CanFocus = true;
			this.button01_.Name = "button01_";
			this.button01_.UseUnderline = true;
			this.button01_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox17.Add(this.button01_);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.button01_]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button02_ = new global::Gtk.Button();
			this.button02_.WidthRequest = 100;
			this.button02_.CanFocus = true;
			this.button02_.Name = "button02_";
			this.button02_.UseUnderline = true;
			this.button02_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox17.Add(this.button02_);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.button02_]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button03_ = new global::Gtk.Button();
			this.button03_.WidthRequest = 100;
			this.button03_.CanFocus = true;
			this.button03_.Name = "button03_";
			this.button03_.UseUnderline = true;
			this.button03_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox17.Add(this.button03_);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.button03_]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button04_ = new global::Gtk.Button();
			this.button04_.WidthRequest = 100;
			this.button04_.CanFocus = true;
			this.button04_.Name = "button04_";
			this.button04_.UseUnderline = true;
			this.button04_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox17.Add(this.button04_);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.button04_]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox5.Add(this.hbox17);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox17]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button10_ = new global::Gtk.Button();
			this.button10_.WidthRequest = 100;
			this.button10_.CanFocus = true;
			this.button10_.Name = "button10_";
			this.button10_.UseUnderline = true;
			this.button10_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox18.Add(this.button10_);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.button10_]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button11_ = new global::Gtk.Button();
			this.button11_.WidthRequest = 100;
			this.button11_.CanFocus = true;
			this.button11_.Name = "button11_";
			this.button11_.UseUnderline = true;
			this.button11_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox18.Add(this.button11_);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.button11_]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button12_ = new global::Gtk.Button();
			this.button12_.WidthRequest = 100;
			this.button12_.CanFocus = true;
			this.button12_.Name = "button12_";
			this.button12_.UseUnderline = true;
			this.button12_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox18.Add(this.button12_);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.button12_]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button13_ = new global::Gtk.Button();
			this.button13_.WidthRequest = 100;
			this.button13_.CanFocus = true;
			this.button13_.Name = "button13_";
			this.button13_.UseUnderline = true;
			this.button13_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox18.Add(this.button13_);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.button13_]));
			w24.Position = 3;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button14_ = new global::Gtk.Button();
			this.button14_.WidthRequest = 100;
			this.button14_.CanFocus = true;
			this.button14_.Name = "button14_";
			this.button14_.UseUnderline = true;
			this.button14_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox18.Add(this.button14_);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.button14_]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox5.Add(this.hbox18);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox18]));
			w26.Position = 4;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button20_ = new global::Gtk.Button();
			this.button20_.WidthRequest = 100;
			this.button20_.CanFocus = true;
			this.button20_.Name = "button20_";
			this.button20_.UseUnderline = true;
			this.button20_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox19.Add(this.button20_);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.button20_]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button21_ = new global::Gtk.Button();
			this.button21_.WidthRequest = 100;
			this.button21_.CanFocus = true;
			this.button21_.Name = "button21_";
			this.button21_.UseUnderline = true;
			this.button21_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox19.Add(this.button21_);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.button21_]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button22_ = new global::Gtk.Button();
			this.button22_.WidthRequest = 100;
			this.button22_.CanFocus = true;
			this.button22_.Name = "button22_";
			this.button22_.UseUnderline = true;
			this.button22_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox19.Add(this.button22_);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.button22_]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button23_ = new global::Gtk.Button();
			this.button23_.WidthRequest = 100;
			this.button23_.CanFocus = true;
			this.button23_.Name = "button23_";
			this.button23_.UseUnderline = true;
			this.button23_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox19.Add(this.button23_);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.button23_]));
			w30.Position = 3;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button24_ = new global::Gtk.Button();
			this.button24_.WidthRequest = 100;
			this.button24_.CanFocus = true;
			this.button24_.Name = "button24_";
			this.button24_.UseUnderline = true;
			this.button24_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox19.Add(this.button24_);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.button24_]));
			w31.Position = 4;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox5.Add(this.hbox19);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox19]));
			w32.Position = 5;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button30_ = new global::Gtk.Button();
			this.button30_.WidthRequest = 100;
			this.button30_.CanFocus = true;
			this.button30_.Name = "button30_";
			this.button30_.UseUnderline = true;
			this.button30_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox20.Add(this.button30_);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button30_]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button31_ = new global::Gtk.Button();
			this.button31_.WidthRequest = 100;
			this.button31_.CanFocus = true;
			this.button31_.Name = "button31_";
			this.button31_.UseUnderline = true;
			this.button31_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox20.Add(this.button31_);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button31_]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button32_ = new global::Gtk.Button();
			this.button32_.WidthRequest = 100;
			this.button32_.CanFocus = true;
			this.button32_.Name = "button32_";
			this.button32_.UseUnderline = true;
			this.button32_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox20.Add(this.button32_);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button32_]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button33_ = new global::Gtk.Button();
			this.button33_.WidthRequest = 100;
			this.button33_.CanFocus = true;
			this.button33_.Name = "button33_";
			this.button33_.UseUnderline = true;
			this.button33_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox20.Add(this.button33_);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button33_]));
			w36.Position = 3;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button34_ = new global::Gtk.Button();
			this.button34_.WidthRequest = 100;
			this.button34_.CanFocus = true;
			this.button34_.Name = "button34_";
			this.button34_.UseUnderline = true;
			this.button34_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox20.Add(this.button34_);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button34_]));
			w37.Position = 4;
			w37.Expand = false;
			w37.Fill = false;
			this.vbox5.Add(this.hbox20);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox20]));
			w38.Position = 6;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.button40_ = new global::Gtk.Button();
			this.button40_.WidthRequest = 100;
			this.button40_.CanFocus = true;
			this.button40_.Name = "button40_";
			this.button40_.UseUnderline = true;
			this.button40_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox21.Add(this.button40_);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.button40_]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.button41_ = new global::Gtk.Button();
			this.button41_.WidthRequest = 100;
			this.button41_.CanFocus = true;
			this.button41_.Name = "button41_";
			this.button41_.UseUnderline = true;
			this.button41_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox21.Add(this.button41_);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.button41_]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.button42_ = new global::Gtk.Button();
			this.button42_.WidthRequest = 100;
			this.button42_.CanFocus = true;
			this.button42_.Name = "button42_";
			this.button42_.UseUnderline = true;
			this.button42_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox21.Add(this.button42_);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.button42_]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.button43_ = new global::Gtk.Button();
			this.button43_.WidthRequest = 100;
			this.button43_.CanFocus = true;
			this.button43_.Name = "button43_";
			this.button43_.UseUnderline = true;
			this.button43_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox21.Add(this.button43_);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.button43_]));
			w42.Position = 3;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.button44_ = new global::Gtk.Button();
			this.button44_.WidthRequest = 100;
			this.button44_.CanFocus = true;
			this.button44_.Name = "button44_";
			this.button44_.UseUnderline = true;
			this.button44_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox21.Add(this.button44_);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.button44_]));
			w43.Position = 4;
			w43.Expand = false;
			w43.Fill = false;
			this.vbox5.Add(this.hbox21);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox21]));
			w44.Position = 7;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.button50_ = new global::Gtk.Button();
			this.button50_.WidthRequest = 100;
			this.button50_.CanFocus = true;
			this.button50_.Name = "button50_";
			this.button50_.UseUnderline = true;
			this.button50_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox22.Add(this.button50_);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.button50_]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.button51_ = new global::Gtk.Button();
			this.button51_.WidthRequest = 100;
			this.button51_.CanFocus = true;
			this.button51_.Name = "button51_";
			this.button51_.UseUnderline = true;
			this.button51_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox22.Add(this.button51_);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.button51_]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.button52_ = new global::Gtk.Button();
			this.button52_.WidthRequest = 100;
			this.button52_.CanFocus = true;
			this.button52_.Name = "button52_";
			this.button52_.UseUnderline = true;
			this.button52_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox22.Add(this.button52_);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.button52_]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.button53_ = new global::Gtk.Button();
			this.button53_.WidthRequest = 100;
			this.button53_.CanFocus = true;
			this.button53_.Name = "button53_";
			this.button53_.UseUnderline = true;
			this.button53_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox22.Add(this.button53_);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.button53_]));
			w48.Position = 3;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.button54_ = new global::Gtk.Button();
			this.button54_.WidthRequest = 100;
			this.button54_.CanFocus = true;
			this.button54_.Name = "button54_";
			this.button54_.UseUnderline = true;
			this.button54_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox22.Add(this.button54_);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.button54_]));
			w49.Position = 4;
			w49.Expand = false;
			w49.Fill = false;
			this.vbox5.Add(this.hbox22);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox22]));
			w50.Position = 8;
			w50.Expand = false;
			w50.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.button60_ = new global::Gtk.Button();
			this.button60_.WidthRequest = 100;
			this.button60_.CanFocus = true;
			this.button60_.Name = "button60_";
			this.button60_.UseUnderline = true;
			this.button60_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox23.Add(this.button60_);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button60_]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.button61_ = new global::Gtk.Button();
			this.button61_.WidthRequest = 100;
			this.button61_.CanFocus = true;
			this.button61_.Name = "button61_";
			this.button61_.UseUnderline = true;
			this.button61_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox23.Add(this.button61_);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button61_]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.button62_ = new global::Gtk.Button();
			this.button62_.WidthRequest = 100;
			this.button62_.CanFocus = true;
			this.button62_.Name = "button62_";
			this.button62_.UseUnderline = true;
			this.button62_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox23.Add(this.button62_);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button62_]));
			w53.Position = 2;
			w53.Expand = false;
			w53.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.button63_ = new global::Gtk.Button();
			this.button63_.WidthRequest = 100;
			this.button63_.CanFocus = true;
			this.button63_.Name = "button63_";
			this.button63_.UseUnderline = true;
			this.button63_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox23.Add(this.button63_);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button63_]));
			w54.Position = 3;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.button64_ = new global::Gtk.Button();
			this.button64_.WidthRequest = 100;
			this.button64_.CanFocus = true;
			this.button64_.Name = "button64_";
			this.button64_.UseUnderline = true;
			this.button64_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox23.Add(this.button64_);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button64_]));
			w55.Position = 4;
			w55.Expand = false;
			w55.Fill = false;
			this.vbox5.Add(this.hbox23);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox23]));
			w56.Position = 9;
			w56.Expand = false;
			w56.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Poslijepodne");
			this.vbox5.Add(this.label13);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label13]));
			w57.Position = 10;
			w57.Expand = false;
			w57.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button70_ = new global::Gtk.Button();
			this.button70_.WidthRequest = 100;
			this.button70_.CanFocus = true;
			this.button70_.Name = "button70_";
			this.button70_.UseUnderline = true;
			this.button70_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox24.Add(this.button70_);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.button70_]));
			w58.Position = 0;
			w58.Expand = false;
			w58.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button71_ = new global::Gtk.Button();
			this.button71_.WidthRequest = 100;
			this.button71_.CanFocus = true;
			this.button71_.Name = "button71_";
			this.button71_.UseUnderline = true;
			this.button71_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox24.Add(this.button71_);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.button71_]));
			w59.Position = 1;
			w59.Expand = false;
			w59.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button72_ = new global::Gtk.Button();
			this.button72_.WidthRequest = 100;
			this.button72_.CanFocus = true;
			this.button72_.Name = "button72_";
			this.button72_.UseUnderline = true;
			this.button72_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox24.Add(this.button72_);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.button72_]));
			w60.Position = 2;
			w60.Expand = false;
			w60.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button73_ = new global::Gtk.Button();
			this.button73_.WidthRequest = 100;
			this.button73_.CanFocus = true;
			this.button73_.Name = "button73_";
			this.button73_.UseUnderline = true;
			this.button73_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox24.Add(this.button73_);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.button73_]));
			w61.Position = 3;
			w61.Expand = false;
			w61.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button74_ = new global::Gtk.Button();
			this.button74_.WidthRequest = 100;
			this.button74_.CanFocus = true;
			this.button74_.Name = "button74_";
			this.button74_.UseUnderline = true;
			this.button74_.Label = global::Mono.Unix.Catalog.GetString("1. Sat");
			this.hbox24.Add(this.button74_);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.button74_]));
			w62.Position = 4;
			w62.Expand = false;
			w62.Fill = false;
			this.vbox5.Add(this.hbox24);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox24]));
			w63.Position = 11;
			w63.Expand = false;
			w63.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.button80_ = new global::Gtk.Button();
			this.button80_.WidthRequest = 100;
			this.button80_.CanFocus = true;
			this.button80_.Name = "button80_";
			this.button80_.UseUnderline = true;
			this.button80_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox25.Add(this.button80_);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.button80_]));
			w64.Position = 0;
			w64.Expand = false;
			w64.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.button81_ = new global::Gtk.Button();
			this.button81_.WidthRequest = 100;
			this.button81_.CanFocus = true;
			this.button81_.Name = "button81_";
			this.button81_.UseUnderline = true;
			this.button81_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox25.Add(this.button81_);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.button81_]));
			w65.Position = 1;
			w65.Expand = false;
			w65.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.button82_ = new global::Gtk.Button();
			this.button82_.WidthRequest = 100;
			this.button82_.CanFocus = true;
			this.button82_.Name = "button82_";
			this.button82_.UseUnderline = true;
			this.button82_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox25.Add(this.button82_);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.button82_]));
			w66.Position = 2;
			w66.Expand = false;
			w66.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.button83_ = new global::Gtk.Button();
			this.button83_.WidthRequest = 100;
			this.button83_.CanFocus = true;
			this.button83_.Name = "button83_";
			this.button83_.UseUnderline = true;
			this.button83_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox25.Add(this.button83_);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.button83_]));
			w67.Position = 3;
			w67.Expand = false;
			w67.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.button84_ = new global::Gtk.Button();
			this.button84_.WidthRequest = 100;
			this.button84_.CanFocus = true;
			this.button84_.Name = "button84_";
			this.button84_.UseUnderline = true;
			this.button84_.Label = global::Mono.Unix.Catalog.GetString("2. Sat");
			this.hbox25.Add(this.button84_);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.button84_]));
			w68.Position = 4;
			w68.Expand = false;
			w68.Fill = false;
			this.vbox5.Add(this.hbox25);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox25]));
			w69.Position = 12;
			w69.Expand = false;
			w69.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.button90_ = new global::Gtk.Button();
			this.button90_.WidthRequest = 100;
			this.button90_.CanFocus = true;
			this.button90_.Name = "button90_";
			this.button90_.UseUnderline = true;
			this.button90_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox26.Add(this.button90_);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.button90_]));
			w70.Position = 0;
			w70.Expand = false;
			w70.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.button91_ = new global::Gtk.Button();
			this.button91_.WidthRequest = 100;
			this.button91_.CanFocus = true;
			this.button91_.Name = "button91_";
			this.button91_.UseUnderline = true;
			this.button91_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox26.Add(this.button91_);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.button91_]));
			w71.Position = 1;
			w71.Expand = false;
			w71.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.button92_ = new global::Gtk.Button();
			this.button92_.WidthRequest = 100;
			this.button92_.CanFocus = true;
			this.button92_.Name = "button92_";
			this.button92_.UseUnderline = true;
			this.button92_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox26.Add(this.button92_);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.button92_]));
			w72.Position = 2;
			w72.Expand = false;
			w72.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.button93_ = new global::Gtk.Button();
			this.button93_.WidthRequest = 100;
			this.button93_.CanFocus = true;
			this.button93_.Name = "button93_";
			this.button93_.UseUnderline = true;
			this.button93_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox26.Add(this.button93_);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.button93_]));
			w73.Position = 3;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.button94_ = new global::Gtk.Button();
			this.button94_.WidthRequest = 100;
			this.button94_.CanFocus = true;
			this.button94_.Name = "button94_";
			this.button94_.UseUnderline = true;
			this.button94_.Label = global::Mono.Unix.Catalog.GetString("3. Sat");
			this.hbox26.Add(this.button94_);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.button94_]));
			w74.Position = 4;
			w74.Expand = false;
			w74.Fill = false;
			this.vbox5.Add(this.hbox26);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox26]));
			w75.Position = 13;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.button100_ = new global::Gtk.Button();
			this.button100_.WidthRequest = 100;
			this.button100_.CanFocus = true;
			this.button100_.Name = "button100_";
			this.button100_.UseUnderline = true;
			this.button100_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox27.Add(this.button100_);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.button100_]));
			w76.Position = 0;
			w76.Expand = false;
			w76.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.button101_ = new global::Gtk.Button();
			this.button101_.WidthRequest = 100;
			this.button101_.CanFocus = true;
			this.button101_.Name = "button101_";
			this.button101_.UseUnderline = true;
			this.button101_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox27.Add(this.button101_);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.button101_]));
			w77.Position = 1;
			w77.Expand = false;
			w77.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.button102_ = new global::Gtk.Button();
			this.button102_.WidthRequest = 100;
			this.button102_.CanFocus = true;
			this.button102_.Name = "button102_";
			this.button102_.UseUnderline = true;
			this.button102_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox27.Add(this.button102_);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.button102_]));
			w78.Position = 2;
			w78.Expand = false;
			w78.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.button103_ = new global::Gtk.Button();
			this.button103_.WidthRequest = 100;
			this.button103_.CanFocus = true;
			this.button103_.Name = "button103_";
			this.button103_.UseUnderline = true;
			this.button103_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox27.Add(this.button103_);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.button103_]));
			w79.Position = 3;
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.button104_ = new global::Gtk.Button();
			this.button104_.WidthRequest = 100;
			this.button104_.CanFocus = true;
			this.button104_.Name = "button104_";
			this.button104_.UseUnderline = true;
			this.button104_.Label = global::Mono.Unix.Catalog.GetString("4. Sat");
			this.hbox27.Add(this.button104_);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.button104_]));
			w80.Position = 4;
			w80.Expand = false;
			w80.Fill = false;
			this.vbox5.Add(this.hbox27);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox27]));
			w81.Position = 14;
			w81.Expand = false;
			w81.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.button110_ = new global::Gtk.Button();
			this.button110_.WidthRequest = 100;
			this.button110_.CanFocus = true;
			this.button110_.Name = "button110_";
			this.button110_.UseUnderline = true;
			this.button110_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox28.Add(this.button110_);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.button110_]));
			w82.Position = 0;
			w82.Expand = false;
			w82.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.button111_ = new global::Gtk.Button();
			this.button111_.WidthRequest = 100;
			this.button111_.CanFocus = true;
			this.button111_.Name = "button111_";
			this.button111_.UseUnderline = true;
			this.button111_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox28.Add(this.button111_);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.button111_]));
			w83.Position = 1;
			w83.Expand = false;
			w83.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.button112_ = new global::Gtk.Button();
			this.button112_.WidthRequest = 100;
			this.button112_.CanFocus = true;
			this.button112_.Name = "button112_";
			this.button112_.UseUnderline = true;
			this.button112_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox28.Add(this.button112_);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.button112_]));
			w84.Position = 2;
			w84.Expand = false;
			w84.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.button113_ = new global::Gtk.Button();
			this.button113_.WidthRequest = 100;
			this.button113_.CanFocus = true;
			this.button113_.Name = "button113_";
			this.button113_.UseUnderline = true;
			this.button113_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox28.Add(this.button113_);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.button113_]));
			w85.Position = 3;
			w85.Expand = false;
			w85.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.button114_ = new global::Gtk.Button();
			this.button114_.WidthRequest = 100;
			this.button114_.CanFocus = true;
			this.button114_.Name = "button114_";
			this.button114_.UseUnderline = true;
			this.button114_.Label = global::Mono.Unix.Catalog.GetString("5. Sat");
			this.hbox28.Add(this.button114_);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.button114_]));
			w86.Position = 4;
			w86.Expand = false;
			w86.Fill = false;
			this.vbox5.Add(this.hbox28);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox28]));
			w87.Position = 15;
			w87.Expand = false;
			w87.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox29 = new global::Gtk.HBox();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.button120_ = new global::Gtk.Button();
			this.button120_.WidthRequest = 100;
			this.button120_.CanFocus = true;
			this.button120_.Name = "button120_";
			this.button120_.UseUnderline = true;
			this.button120_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox29.Add(this.button120_);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.button120_]));
			w88.Position = 0;
			w88.Expand = false;
			w88.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.button121_ = new global::Gtk.Button();
			this.button121_.WidthRequest = 100;
			this.button121_.CanFocus = true;
			this.button121_.Name = "button121_";
			this.button121_.UseUnderline = true;
			this.button121_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox29.Add(this.button121_);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.button121_]));
			w89.Position = 1;
			w89.Expand = false;
			w89.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.button122_ = new global::Gtk.Button();
			this.button122_.WidthRequest = 100;
			this.button122_.CanFocus = true;
			this.button122_.Name = "button122_";
			this.button122_.UseUnderline = true;
			this.button122_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox29.Add(this.button122_);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.button122_]));
			w90.Position = 2;
			w90.Expand = false;
			w90.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.button123_ = new global::Gtk.Button();
			this.button123_.WidthRequest = 100;
			this.button123_.CanFocus = true;
			this.button123_.Name = "button123_";
			this.button123_.UseUnderline = true;
			this.button123_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox29.Add(this.button123_);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.button123_]));
			w91.Position = 3;
			w91.Expand = false;
			w91.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.button124_ = new global::Gtk.Button();
			this.button124_.WidthRequest = 100;
			this.button124_.CanFocus = true;
			this.button124_.Name = "button124_";
			this.button124_.UseUnderline = true;
			this.button124_.Label = global::Mono.Unix.Catalog.GetString("6. Sat");
			this.hbox29.Add(this.button124_);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.button124_]));
			w92.Position = 4;
			w92.Expand = false;
			w92.Fill = false;
			this.vbox5.Add(this.hbox29);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox29]));
			w93.Position = 16;
			w93.Expand = false;
			w93.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox30 = new global::Gtk.HBox();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.button130_ = new global::Gtk.Button();
			this.button130_.WidthRequest = 100;
			this.button130_.CanFocus = true;
			this.button130_.Name = "button130_";
			this.button130_.UseUnderline = true;
			this.button130_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox30.Add(this.button130_);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.button130_]));
			w94.Position = 0;
			w94.Expand = false;
			w94.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.button131_ = new global::Gtk.Button();
			this.button131_.WidthRequest = 100;
			this.button131_.CanFocus = true;
			this.button131_.Name = "button131_";
			this.button131_.UseUnderline = true;
			this.button131_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox30.Add(this.button131_);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.button131_]));
			w95.Position = 1;
			w95.Expand = false;
			w95.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.button132_ = new global::Gtk.Button();
			this.button132_.WidthRequest = 100;
			this.button132_.CanFocus = true;
			this.button132_.Name = "button132_";
			this.button132_.UseUnderline = true;
			this.button132_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox30.Add(this.button132_);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.button132_]));
			w96.Position = 2;
			w96.Expand = false;
			w96.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.button133_ = new global::Gtk.Button();
			this.button133_.WidthRequest = 100;
			this.button133_.CanFocus = true;
			this.button133_.Name = "button133_";
			this.button133_.UseUnderline = true;
			this.button133_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox30.Add(this.button133_);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.button133_]));
			w97.Position = 3;
			w97.Expand = false;
			w97.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.button134_ = new global::Gtk.Button();
			this.button134_.WidthRequest = 100;
			this.button134_.CanFocus = true;
			this.button134_.Name = "button134_";
			this.button134_.UseUnderline = true;
			this.button134_.Label = global::Mono.Unix.Catalog.GetString("7. Sat");
			this.hbox30.Add(this.button134_);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.button134_]));
			w98.Position = 4;
			w98.Expand = false;
			w98.Fill = false;
			this.vbox5.Add(this.hbox30);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox30]));
			w99.Position = 17;
			w99.Expand = false;
			w99.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.button140_ = new global::Gtk.Button();
			this.button140_.WidthRequest = 100;
			this.button140_.CanFocus = true;
			this.button140_.Name = "button140_";
			this.button140_.UseUnderline = true;
			this.button140_.Label = global::Mono.Unix.Catalog.GetString("8. Sat");
			this.hbox31.Add(this.button140_);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.button140_]));
			w100.Position = 0;
			w100.Expand = false;
			w100.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.button141_ = new global::Gtk.Button();
			this.button141_.WidthRequest = 100;
			this.button141_.CanFocus = true;
			this.button141_.Name = "button141_";
			this.button141_.UseUnderline = true;
			this.button141_.Label = global::Mono.Unix.Catalog.GetString("8. Sat");
			this.hbox31.Add(this.button141_);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.button141_]));
			w101.Position = 1;
			w101.Expand = false;
			w101.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.button142_ = new global::Gtk.Button();
			this.button142_.WidthRequest = 100;
			this.button142_.CanFocus = true;
			this.button142_.Name = "button142_";
			this.button142_.UseUnderline = true;
			this.button142_.Label = global::Mono.Unix.Catalog.GetString("8. Sat");
			this.hbox31.Add(this.button142_);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.button142_]));
			w102.Position = 2;
			w102.Expand = false;
			w102.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.button143_ = new global::Gtk.Button();
			this.button143_.WidthRequest = 100;
			this.button143_.CanFocus = true;
			this.button143_.Name = "button143_";
			this.button143_.UseUnderline = true;
			this.button143_.Label = global::Mono.Unix.Catalog.GetString("8. Sat");
			this.hbox31.Add(this.button143_);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.button143_]));
			w103.Position = 3;
			w103.Expand = false;
			w103.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.button144_ = new global::Gtk.Button();
			this.button144_.WidthRequest = 100;
			this.button144_.CanFocus = true;
			this.button144_.Name = "button144_";
			this.button144_.UseUnderline = true;
			this.button144_.Label = global::Mono.Unix.Catalog.GetString("8. Sat");
			this.hbox31.Add(this.button144_);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.button144_]));
			w104.Position = 4;
			w104.Expand = false;
			w104.Fill = false;
			this.vbox5.Add(this.hbox31);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox31]));
			w105.Position = 18;
			w105.Expand = false;
			w105.Fill = false;
			this.hbox14.Add(this.vbox5);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.vbox5]));
			w106.Position = 0;
			w106.Expand = false;
			w106.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Dodatne informacije");
			this.vbox7.Add(this.label14);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label14]));
			w107.Position = 0;
			w107.Expand = false;
			w107.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.WidthRequest = 230;
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w108 = new global::Gtk.Viewport();
			w108.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.hbox32 = new global::Gtk.HBox();
			this.hbox32.Name = "hbox32";
			this.hbox32.Spacing = 6;
			this.hbox32.BorderWidth = ((uint)(5));
			// Container child hbox32.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.WidthRequest = 128;
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Informacije o profesoru:");
			this.vbox8.Add(this.label15);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label15]));
			w109.Position = 0;
			w109.Expand = false;
			w109.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label();
			this.label16.HeightRequest = 20;
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Ime:");
			this.vbox8.Add(this.label16);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label16]));
			w110.Position = 1;
			w110.Expand = false;
			w110.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.HeightRequest = 20;
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Prezime:");
			this.vbox8.Add(this.label17);
			global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label17]));
			w111.Position = 2;
			w111.Expand = false;
			w111.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label();
			this.label18.HeightRequest = 20;
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("OIB:");
			this.vbox8.Add(this.label18);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label18]));
			w112.Position = 3;
			w112.Expand = false;
			w112.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.HeightRequest = 30;
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Dodatni opis:");
			this.vbox8.Add(this.label19);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label19]));
			w113.Position = 4;
			w113.Expand = false;
			w113.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label();
			this.label20.HeightRequest = 30;
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Status:");
			this.vbox8.Add(this.label20);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label20]));
			w114.PackType = ((global::Gtk.PackType)(1));
			w114.Position = 5;
			w114.Expand = false;
			w114.Fill = false;
			this.hbox32.Add(this.vbox8);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.vbox8]));
			w115.Position = 0;
			w115.Expand = false;
			w115.Fill = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.HeightRequest = 15;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.vbox9.Add(this.fixed3);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.fixed3]));
			w116.Position = 0;
			w116.Expand = false;
			w116.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label_ime = new global::Gtk.Label();
			this.label_ime.HeightRequest = 20;
			this.label_ime.Name = "label_ime";
			this.label_ime.Xalign = 0F;
			this.vbox9.Add(this.label_ime);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label_ime]));
			w117.Position = 1;
			w117.Expand = false;
			w117.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label_prezime = new global::Gtk.Label();
			this.label_prezime.HeightRequest = 20;
			this.label_prezime.Name = "label_prezime";
			this.label_prezime.Xalign = 0F;
			this.vbox9.Add(this.label_prezime);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label_prezime]));
			w118.Position = 2;
			w118.Expand = false;
			w118.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label_OIB = new global::Gtk.Label();
			this.label_OIB.HeightRequest = 20;
			this.label_OIB.Name = "label_OIB";
			this.label_OIB.Xalign = 0F;
			this.vbox9.Add(this.label_OIB);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label_OIB]));
			w119.Position = 3;
			w119.Expand = false;
			w119.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label_opis = new global::Gtk.Label();
			this.label_opis.HeightRequest = 30;
			this.label_opis.Name = "label_opis";
			this.label_opis.Xalign = 0F;
			this.vbox9.Add(this.label_opis);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label_opis]));
			w120.Position = 4;
			w120.Expand = false;
			w120.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label_status = new global::Gtk.Label();
			this.label_status.HeightRequest = 30;
			this.label_status.Name = "label_status";
			this.label_status.Xalign = 0F;
			this.vbox9.Add(this.label_status);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label_status]));
			w121.PackType = ((global::Gtk.PackType)(1));
			w121.Position = 5;
			w121.Expand = false;
			w121.Fill = false;
			this.hbox32.Add(this.vbox9);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.vbox9]));
			w122.Position = 1;
			w122.Expand = false;
			w122.Fill = false;
			w108.Add(this.hbox32);
			this.scrolledwindow2.Add(w108);
			this.vbox7.Add(this.scrolledwindow2);
			global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.scrolledwindow2]));
			w125.Position = 1;
			this.frame1.Add(this.vbox7);
			this.hbox14.Add(this.frame1);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.frame1]));
			w127.Position = 1;
			w127.Expand = false;
			w127.Fill = false;
			this.vbox4.Add(this.hbox14);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox14]));
			w128.Position = 0;
			w128.Expand = false;
			w128.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.hbox1.Add(this.fixed5);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed5]));
			w129.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 147;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("_Izlaz");
			this.hbox1.Add(this.button1);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
			w130.Position = 1;
			w130.Expand = false;
			w130.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.hbox1.Add(this.fixed4);
			global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed4]));
			w131.Position = 2;
			this.vbox4.Add(this.hbox1);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
			w132.Position = 1;
			w132.Expand = false;
			w132.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 816;
			this.DefaultHeight = 819;
			this.Show();
			this.button00_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button01_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button02_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button03_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button04_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button10_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button11_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button12_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button13_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button14_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button20_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button21_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button22_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button23_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button24_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button30_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button31_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button32_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button33_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button34_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button40_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button41_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button42_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button43_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button44_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button50_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button51_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button52_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button53_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button54_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button60_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button61_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button62_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button63_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button64_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button70_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button71_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button72_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button73_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button74_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button80_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button81_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button82_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button83_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button84_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button90_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button91_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button92_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button93_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button94_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button100_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button101_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button102_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button103_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button104_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button110_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button111_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button112_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button113_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button114_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button120_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button121_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button122_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button123_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button124_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button130_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button131_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button132_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button133_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button134_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button140_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button141_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button142_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button143_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button144_.Entered += new global::System.EventHandler(this.OnButtonEntered);
			this.button1.Clicked += new global::System.EventHandler(this.OnButtonIzlazClicked);
		}
	}
}
