
// This file has been generated by the GUI designer. Do not modify.
namespace Raspored
{
	public partial class ZauzmiTerminWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button button00_;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button button01_;

		private global::Gtk.Button button02_;

		private global::Gtk.Button button03_;

		private global::Gtk.Button button04_;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Button button10_;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Button button11_;

		private global::Gtk.Button button12_;

		private global::Gtk.Button button13_;

		private global::Gtk.Button button14_;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button button20_;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Button button21_;

		private global::Gtk.Button button22_;

		private global::Gtk.Button button23_;

		private global::Gtk.Button button24_;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Button button30_;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Button button31_;

		private global::Gtk.Button button32_;

		private global::Gtk.Button button33_;

		private global::Gtk.Button button34_;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Button button40_;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button button41_;

		private global::Gtk.Button button42_;

		private global::Gtk.Button button43_;

		private global::Gtk.Button button44_;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Button button50_;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Button button51_;

		private global::Gtk.Button button52_;

		private global::Gtk.Button button53_;

		private global::Gtk.Button button54_;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Button button60_;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Button button61_;

		private global::Gtk.Button button62_;

		private global::Gtk.Button button63_;

		private global::Gtk.Button button64_;

		private global::Gtk.Label label2;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Button button70_;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Button button71_;

		private global::Gtk.Button button72_;

		private global::Gtk.Button button73_;

		private global::Gtk.Button button74_;

		private global::Gtk.HBox hbox19;

		private global::Gtk.Button button80_;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Button button81_;

		private global::Gtk.Button button82_;

		private global::Gtk.Button button83_;

		private global::Gtk.Button button84_;

		private global::Gtk.HBox hbox21;

		private global::Gtk.Button button90_;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Button button91_;

		private global::Gtk.Button button92_;

		private global::Gtk.Button button93_;

		private global::Gtk.Button button94_;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox23;

		private global::Gtk.Button button100_;

		private global::Gtk.HBox hbox24;

		private global::Gtk.Button button101_;

		private global::Gtk.Button button102_;

		private global::Gtk.Button button103_;

		private global::Gtk.Button button104_;

		private global::Gtk.VBox vbox10;

		private global::Gtk.HBox hbox25;

		private global::Gtk.Button button110_;

		private global::Gtk.HBox hbox26;

		private global::Gtk.Button button111_;

		private global::Gtk.Button button112_;

		private global::Gtk.Button button113_;

		private global::Gtk.Button button114_;

		private global::Gtk.HBox hbox27;

		private global::Gtk.Button button120_;

		private global::Gtk.HBox hbox28;

		private global::Gtk.Button button121_;

		private global::Gtk.Button button122_;

		private global::Gtk.Button button123_;

		private global::Gtk.Button button124_;

		private global::Gtk.HBox hbox29;

		private global::Gtk.Button button130_;

		private global::Gtk.HBox hbox30;

		private global::Gtk.Button button131_;

		private global::Gtk.Button button132_;

		private global::Gtk.Button button133_;

		private global::Gtk.Button button134_;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox31;

		private global::Gtk.Button button140_;

		private global::Gtk.HBox hbox32;

		private global::Gtk.Button button141_;

		private global::Gtk.Button button142_;

		private global::Gtk.Button button143_;

		private global::Gtk.Button button144_;

		private global::Gtk.HBox hbox33;

		private global::Gtk.Button button_spremi;

		private global::Gtk.Button button_odustani;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Raspored.ZauzmiTerminWindow
			this.HeightRequest = 620;
			this.Name = "Raspored.ZauzmiTerminWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Zauzmi termin");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("Raspored.Logo_smanjeni.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.BorderWidth = ((uint)(30));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Raspored.ZauzmiTerminWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Prijepodne:");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 100;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Ponedjeljak");
			this.hbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 102;
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Utorak");
			this.hbox2.Add(this.label4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.WidthRequest = 97;
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Srijeda");
			this.hbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 106;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Četvrtak");
			this.hbox2.Add(this.label6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label6]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 90;
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Petak");
			this.hbox1.Add(this.label7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label7]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox8.Add(this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button00_ = new global::Gtk.Button();
			this.button00_.WidthRequest = 100;
			this.button00_.CanFocus = true;
			this.button00_.Name = "button00_";
			this.button00_.UseUnderline = true;
			this.button00_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox3.Add(this.button00_);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button00_]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button01_ = new global::Gtk.Button();
			this.button01_.WidthRequest = 100;
			this.button01_.CanFocus = true;
			this.button01_.Name = "button01_";
			this.button01_.UseUnderline = true;
			this.button01_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox4.Add(this.button01_);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button01_]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button02_ = new global::Gtk.Button();
			this.button02_.WidthRequest = 100;
			this.button02_.CanFocus = true;
			this.button02_.Name = "button02_";
			this.button02_.UseUnderline = true;
			this.button02_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox4.Add(this.button02_);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button02_]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button03_ = new global::Gtk.Button();
			this.button03_.WidthRequest = 100;
			this.button03_.CanFocus = true;
			this.button03_.Name = "button03_";
			this.button03_.UseUnderline = true;
			this.button03_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox4.Add(this.button03_);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button03_]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button04_ = new global::Gtk.Button();
			this.button04_.WidthRequest = 100;
			this.button04_.CanFocus = true;
			this.button04_.Name = "button04_";
			this.button04_.UseUnderline = true;
			this.button04_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox3.Add(this.button04_);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button04_]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox8.Add(this.hbox3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox3]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.button10_ = new global::Gtk.Button();
			this.button10_.WidthRequest = 100;
			this.button10_.CanFocus = true;
			this.button10_.Name = "button10_";
			this.button10_.UseUnderline = true;
			this.button10_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox5.Add(this.button10_);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button10_]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.button11_ = new global::Gtk.Button();
			this.button11_.WidthRequest = 100;
			this.button11_.CanFocus = true;
			this.button11_.Name = "button11_";
			this.button11_.UseUnderline = true;
			this.button11_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox6.Add(this.button11_);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.button11_]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.button12_ = new global::Gtk.Button();
			this.button12_.WidthRequest = 100;
			this.button12_.CanFocus = true;
			this.button12_.Name = "button12_";
			this.button12_.UseUnderline = true;
			this.button12_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox6.Add(this.button12_);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.button12_]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.button13_ = new global::Gtk.Button();
			this.button13_.WidthRequest = 100;
			this.button13_.CanFocus = true;
			this.button13_.Name = "button13_";
			this.button13_.UseUnderline = true;
			this.button13_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox6.Add(this.button13_);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.button13_]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox5.Add(this.hbox6);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox6]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.button14_ = new global::Gtk.Button();
			this.button14_.WidthRequest = 100;
			this.button14_.CanFocus = true;
			this.button14_.Name = "button14_";
			this.button14_.UseUnderline = true;
			this.button14_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox5.Add(this.button14_);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button14_]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox8.Add(this.hbox5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox5]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox3.Add(this.vbox8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox8]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button20_ = new global::Gtk.Button();
			this.button20_.WidthRequest = 100;
			this.button20_.CanFocus = true;
			this.button20_.Name = "button20_";
			this.button20_.UseUnderline = true;
			this.button20_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox7.Add(this.button20_);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button20_]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button21_ = new global::Gtk.Button();
			this.button21_.WidthRequest = 100;
			this.button21_.CanFocus = true;
			this.button21_.Name = "button21_";
			this.button21_.UseUnderline = true;
			this.button21_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox8.Add(this.button21_);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button21_]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button22_ = new global::Gtk.Button();
			this.button22_.WidthRequest = 100;
			this.button22_.CanFocus = true;
			this.button22_.Name = "button22_";
			this.button22_.UseUnderline = true;
			this.button22_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox8.Add(this.button22_);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button22_]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button23_ = new global::Gtk.Button();
			this.button23_.WidthRequest = 100;
			this.button23_.CanFocus = true;
			this.button23_.Name = "button23_";
			this.button23_.UseUnderline = true;
			this.button23_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox8.Add(this.button23_);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button23_]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox7.Add(this.hbox8);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox8]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button24_ = new global::Gtk.Button();
			this.button24_.WidthRequest = 100;
			this.button24_.CanFocus = true;
			this.button24_.Name = "button24_";
			this.button24_.UseUnderline = true;
			this.button24_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox7.Add(this.button24_);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button24_]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox7.Add(this.hbox7);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button30_ = new global::Gtk.Button();
			this.button30_.WidthRequest = 100;
			this.button30_.CanFocus = true;
			this.button30_.Name = "button30_";
			this.button30_.UseUnderline = true;
			this.button30_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox9.Add(this.button30_);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button30_]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button31_ = new global::Gtk.Button();
			this.button31_.WidthRequest = 100;
			this.button31_.CanFocus = true;
			this.button31_.Name = "button31_";
			this.button31_.UseUnderline = true;
			this.button31_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox10.Add(this.button31_);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button31_]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button32_ = new global::Gtk.Button();
			this.button32_.WidthRequest = 100;
			this.button32_.CanFocus = true;
			this.button32_.Name = "button32_";
			this.button32_.UseUnderline = true;
			this.button32_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox10.Add(this.button32_);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button32_]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button33_ = new global::Gtk.Button();
			this.button33_.WidthRequest = 100;
			this.button33_.CanFocus = true;
			this.button33_.Name = "button33_";
			this.button33_.UseUnderline = true;
			this.button33_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox10.Add(this.button33_);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button33_]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.hbox9.Add(this.hbox10);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox10]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button34_ = new global::Gtk.Button();
			this.button34_.WidthRequest = 100;
			this.button34_.CanFocus = true;
			this.button34_.Name = "button34_";
			this.button34_.UseUnderline = true;
			this.button34_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox9.Add(this.button34_);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button34_]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox7.Add(this.hbox9);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox9]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button40_ = new global::Gtk.Button();
			this.button40_.WidthRequest = 100;
			this.button40_.CanFocus = true;
			this.button40_.Name = "button40_";
			this.button40_.UseUnderline = true;
			this.button40_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox11.Add(this.button40_);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button40_]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button41_ = new global::Gtk.Button();
			this.button41_.WidthRequest = 100;
			this.button41_.CanFocus = true;
			this.button41_.Name = "button41_";
			this.button41_.UseUnderline = true;
			this.button41_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox12.Add(this.button41_);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button41_]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button42_ = new global::Gtk.Button();
			this.button42_.WidthRequest = 100;
			this.button42_.CanFocus = true;
			this.button42_.Name = "button42_";
			this.button42_.UseUnderline = true;
			this.button42_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox12.Add(this.button42_);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button42_]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button43_ = new global::Gtk.Button();
			this.button43_.WidthRequest = 100;
			this.button43_.CanFocus = true;
			this.button43_.Name = "button43_";
			this.button43_.UseUnderline = true;
			this.button43_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox12.Add(this.button43_);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button43_]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			this.hbox11.Add(this.hbox12);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox12]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button44_ = new global::Gtk.Button();
			this.button44_.WidthRequest = 100;
			this.button44_.CanFocus = true;
			this.button44_.Name = "button44_";
			this.button44_.UseUnderline = true;
			this.button44_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox11.Add(this.button44_);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button44_]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			this.vbox7.Add(this.hbox11);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox11]));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			this.vbox3.Add(this.vbox7);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox7]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button50_ = new global::Gtk.Button();
			this.button50_.WidthRequest = 100;
			this.button50_.CanFocus = true;
			this.button50_.Name = "button50_";
			this.button50_.UseUnderline = true;
			this.button50_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox13.Add(this.button50_);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button50_]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.button51_ = new global::Gtk.Button();
			this.button51_.WidthRequest = 100;
			this.button51_.CanFocus = true;
			this.button51_.Name = "button51_";
			this.button51_.UseUnderline = true;
			this.button51_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox14.Add(this.button51_);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.button51_]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.button52_ = new global::Gtk.Button();
			this.button52_.WidthRequest = 100;
			this.button52_.CanFocus = true;
			this.button52_.Name = "button52_";
			this.button52_.UseUnderline = true;
			this.button52_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox14.Add(this.button52_);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.button52_]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.button53_ = new global::Gtk.Button();
			this.button53_.WidthRequest = 100;
			this.button53_.CanFocus = true;
			this.button53_.Name = "button53_";
			this.button53_.UseUnderline = true;
			this.button53_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox14.Add(this.button53_);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.button53_]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			this.hbox13.Add(this.hbox14);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.hbox14]));
			w50.Position = 1;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button54_ = new global::Gtk.Button();
			this.button54_.WidthRequest = 100;
			this.button54_.CanFocus = true;
			this.button54_.Name = "button54_";
			this.button54_.UseUnderline = true;
			this.button54_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox13.Add(this.button54_);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button54_]));
			w51.Position = 2;
			w51.Expand = false;
			w51.Fill = false;
			this.vbox6.Add(this.hbox13);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox13]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.button60_ = new global::Gtk.Button();
			this.button60_.WidthRequest = 100;
			this.button60_.CanFocus = true;
			this.button60_.Name = "button60_";
			this.button60_.UseUnderline = true;
			this.button60_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox15.Add(this.button60_);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.button60_]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.button61_ = new global::Gtk.Button();
			this.button61_.WidthRequest = 100;
			this.button61_.CanFocus = true;
			this.button61_.Name = "button61_";
			this.button61_.UseUnderline = true;
			this.button61_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox16.Add(this.button61_);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.button61_]));
			w54.Position = 0;
			w54.Expand = false;
			w54.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.button62_ = new global::Gtk.Button();
			this.button62_.WidthRequest = 100;
			this.button62_.CanFocus = true;
			this.button62_.Name = "button62_";
			this.button62_.UseUnderline = true;
			this.button62_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox16.Add(this.button62_);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.button62_]));
			w55.Position = 1;
			w55.Expand = false;
			w55.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.button63_ = new global::Gtk.Button();
			this.button63_.WidthRequest = 100;
			this.button63_.CanFocus = true;
			this.button63_.Name = "button63_";
			this.button63_.UseUnderline = true;
			this.button63_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox16.Add(this.button63_);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.button63_]));
			w56.Position = 2;
			w56.Expand = false;
			w56.Fill = false;
			this.hbox15.Add(this.hbox16);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.hbox16]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.button64_ = new global::Gtk.Button();
			this.button64_.WidthRequest = 100;
			this.button64_.CanFocus = true;
			this.button64_.Name = "button64_";
			this.button64_.UseUnderline = true;
			this.button64_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox15.Add(this.button64_);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.button64_]));
			w58.Position = 2;
			w58.Expand = false;
			w58.Fill = false;
			this.vbox6.Add(this.hbox15);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox15]));
			w59.Position = 1;
			w59.Expand = false;
			w59.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Posljepodne:");
			this.vbox6.Add(this.label2);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label2]));
			w60.Position = 2;
			w60.Expand = false;
			w60.Fill = false;
			this.vbox3.Add(this.vbox6);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox6]));
			w61.Position = 2;
			w61.Expand = false;
			w61.Fill = false;
			this.vbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
			w62.Position = 1;
			w62.Expand = false;
			w62.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button70_ = new global::Gtk.Button();
			this.button70_.WidthRequest = 100;
			this.button70_.CanFocus = true;
			this.button70_.Name = "button70_";
			this.button70_.UseUnderline = true;
			this.button70_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox17.Add(this.button70_);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.button70_]));
			w63.Position = 0;
			w63.Expand = false;
			w63.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button71_ = new global::Gtk.Button();
			this.button71_.WidthRequest = 100;
			this.button71_.CanFocus = true;
			this.button71_.Name = "button71_";
			this.button71_.UseUnderline = true;
			this.button71_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox18.Add(this.button71_);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.button71_]));
			w64.Position = 0;
			w64.Expand = false;
			w64.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button72_ = new global::Gtk.Button();
			this.button72_.WidthRequest = 100;
			this.button72_.CanFocus = true;
			this.button72_.Name = "button72_";
			this.button72_.UseUnderline = true;
			this.button72_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox18.Add(this.button72_);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.button72_]));
			w65.Position = 1;
			w65.Expand = false;
			w65.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.button73_ = new global::Gtk.Button();
			this.button73_.WidthRequest = 100;
			this.button73_.CanFocus = true;
			this.button73_.Name = "button73_";
			this.button73_.UseUnderline = true;
			this.button73_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox18.Add(this.button73_);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.button73_]));
			w66.Position = 2;
			w66.Expand = false;
			w66.Fill = false;
			this.hbox17.Add(this.hbox18);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.hbox18]));
			w67.Position = 1;
			w67.Expand = false;
			w67.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.button74_ = new global::Gtk.Button();
			this.button74_.WidthRequest = 100;
			this.button74_.CanFocus = true;
			this.button74_.Name = "button74_";
			this.button74_.UseUnderline = true;
			this.button74_.Label = global::Mono.Unix.Catalog.GetString("1. sat");
			this.hbox17.Add(this.button74_);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.button74_]));
			w68.Position = 2;
			w68.Expand = false;
			w68.Fill = false;
			this.vbox4.Add(this.hbox17);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox17]));
			w69.Position = 0;
			w69.Expand = false;
			w69.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button80_ = new global::Gtk.Button();
			this.button80_.WidthRequest = 100;
			this.button80_.CanFocus = true;
			this.button80_.Name = "button80_";
			this.button80_.UseUnderline = true;
			this.button80_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox19.Add(this.button80_);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.button80_]));
			w70.Position = 0;
			w70.Expand = false;
			w70.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button81_ = new global::Gtk.Button();
			this.button81_.WidthRequest = 100;
			this.button81_.CanFocus = true;
			this.button81_.Name = "button81_";
			this.button81_.UseUnderline = true;
			this.button81_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox20.Add(this.button81_);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button81_]));
			w71.Position = 0;
			w71.Expand = false;
			w71.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button82_ = new global::Gtk.Button();
			this.button82_.WidthRequest = 100;
			this.button82_.CanFocus = true;
			this.button82_.Name = "button82_";
			this.button82_.UseUnderline = true;
			this.button82_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox20.Add(this.button82_);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button82_]));
			w72.Position = 1;
			w72.Expand = false;
			w72.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.button83_ = new global::Gtk.Button();
			this.button83_.WidthRequest = 100;
			this.button83_.CanFocus = true;
			this.button83_.Name = "button83_";
			this.button83_.UseUnderline = true;
			this.button83_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox20.Add(this.button83_);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.button83_]));
			w73.Position = 2;
			w73.Expand = false;
			w73.Fill = false;
			this.hbox19.Add(this.hbox20);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.hbox20]));
			w74.Position = 1;
			w74.Expand = false;
			w74.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button84_ = new global::Gtk.Button();
			this.button84_.WidthRequest = 100;
			this.button84_.CanFocus = true;
			this.button84_.Name = "button84_";
			this.button84_.UseUnderline = true;
			this.button84_.Label = global::Mono.Unix.Catalog.GetString("2. sat");
			this.hbox19.Add(this.button84_);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.button84_]));
			w75.Position = 2;
			w75.Expand = false;
			w75.Fill = false;
			this.vbox4.Add(this.hbox19);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox19]));
			w76.Position = 1;
			w76.Expand = false;
			w76.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.button90_ = new global::Gtk.Button();
			this.button90_.WidthRequest = 100;
			this.button90_.CanFocus = true;
			this.button90_.Name = "button90_";
			this.button90_.UseUnderline = true;
			this.button90_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox21.Add(this.button90_);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.button90_]));
			w77.Position = 0;
			w77.Expand = false;
			w77.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.button91_ = new global::Gtk.Button();
			this.button91_.WidthRequest = 100;
			this.button91_.CanFocus = true;
			this.button91_.Name = "button91_";
			this.button91_.UseUnderline = true;
			this.button91_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox22.Add(this.button91_);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.button91_]));
			w78.Position = 0;
			w78.Expand = false;
			w78.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.button92_ = new global::Gtk.Button();
			this.button92_.WidthRequest = 100;
			this.button92_.CanFocus = true;
			this.button92_.Name = "button92_";
			this.button92_.UseUnderline = true;
			this.button92_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox22.Add(this.button92_);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.button92_]));
			w79.Position = 1;
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.button93_ = new global::Gtk.Button();
			this.button93_.WidthRequest = 100;
			this.button93_.CanFocus = true;
			this.button93_.Name = "button93_";
			this.button93_.UseUnderline = true;
			this.button93_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox22.Add(this.button93_);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.button93_]));
			w80.Position = 2;
			w80.Expand = false;
			w80.Fill = false;
			this.hbox21.Add(this.hbox22);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.hbox22]));
			w81.Position = 1;
			w81.Expand = false;
			w81.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.button94_ = new global::Gtk.Button();
			this.button94_.WidthRequest = 100;
			this.button94_.CanFocus = true;
			this.button94_.Name = "button94_";
			this.button94_.UseUnderline = true;
			this.button94_.Label = global::Mono.Unix.Catalog.GetString("3. sat");
			this.hbox21.Add(this.button94_);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.button94_]));
			w82.Position = 2;
			w82.Expand = false;
			w82.Fill = false;
			this.vbox4.Add(this.hbox21);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox21]));
			w83.Position = 2;
			w83.Expand = false;
			w83.Fill = false;
			this.vbox2.Add(this.vbox4);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
			w84.Position = 0;
			w84.Expand = false;
			w84.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.button100_ = new global::Gtk.Button();
			this.button100_.WidthRequest = 100;
			this.button100_.CanFocus = true;
			this.button100_.Name = "button100_";
			this.button100_.UseUnderline = true;
			this.button100_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox23.Add(this.button100_);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button100_]));
			w85.Position = 0;
			w85.Expand = false;
			w85.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button101_ = new global::Gtk.Button();
			this.button101_.WidthRequest = 100;
			this.button101_.CanFocus = true;
			this.button101_.Name = "button101_";
			this.button101_.UseUnderline = true;
			this.button101_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox24.Add(this.button101_);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.button101_]));
			w86.Position = 0;
			w86.Expand = false;
			w86.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button102_ = new global::Gtk.Button();
			this.button102_.WidthRequest = 100;
			this.button102_.CanFocus = true;
			this.button102_.Name = "button102_";
			this.button102_.UseUnderline = true;
			this.button102_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox24.Add(this.button102_);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.button102_]));
			w87.Position = 1;
			w87.Expand = false;
			w87.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.button103_ = new global::Gtk.Button();
			this.button103_.WidthRequest = 100;
			this.button103_.CanFocus = true;
			this.button103_.Name = "button103_";
			this.button103_.UseUnderline = true;
			this.button103_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox24.Add(this.button103_);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.button103_]));
			w88.Position = 2;
			w88.Expand = false;
			w88.Fill = false;
			this.hbox23.Add(this.hbox24);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.hbox24]));
			w89.Position = 1;
			w89.Expand = false;
			w89.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.button104_ = new global::Gtk.Button();
			this.button104_.WidthRequest = 100;
			this.button104_.CanFocus = true;
			this.button104_.Name = "button104_";
			this.button104_.UseUnderline = true;
			this.button104_.Label = global::Mono.Unix.Catalog.GetString("4. sat");
			this.hbox23.Add(this.button104_);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.button104_]));
			w90.Position = 2;
			w90.Expand = false;
			w90.Fill = false;
			this.vbox5.Add(this.hbox23);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox23]));
			w91.Position = 0;
			w91.Expand = false;
			w91.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.button110_ = new global::Gtk.Button();
			this.button110_.WidthRequest = 100;
			this.button110_.CanFocus = true;
			this.button110_.Name = "button110_";
			this.button110_.UseUnderline = true;
			this.button110_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox25.Add(this.button110_);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.button110_]));
			w92.Position = 0;
			w92.Expand = false;
			w92.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.button111_ = new global::Gtk.Button();
			this.button111_.WidthRequest = 100;
			this.button111_.CanFocus = true;
			this.button111_.Name = "button111_";
			this.button111_.UseUnderline = true;
			this.button111_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox26.Add(this.button111_);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.button111_]));
			w93.Position = 0;
			w93.Expand = false;
			w93.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.button112_ = new global::Gtk.Button();
			this.button112_.WidthRequest = 100;
			this.button112_.CanFocus = true;
			this.button112_.Name = "button112_";
			this.button112_.UseUnderline = true;
			this.button112_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox26.Add(this.button112_);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.button112_]));
			w94.Position = 1;
			w94.Expand = false;
			w94.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.button113_ = new global::Gtk.Button();
			this.button113_.WidthRequest = 100;
			this.button113_.CanFocus = true;
			this.button113_.Name = "button113_";
			this.button113_.UseUnderline = true;
			this.button113_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox26.Add(this.button113_);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.button113_]));
			w95.Position = 2;
			w95.Expand = false;
			w95.Fill = false;
			this.hbox25.Add(this.hbox26);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.hbox26]));
			w96.Position = 1;
			w96.Expand = false;
			w96.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.button114_ = new global::Gtk.Button();
			this.button114_.WidthRequest = 100;
			this.button114_.CanFocus = true;
			this.button114_.Name = "button114_";
			this.button114_.UseUnderline = true;
			this.button114_.Label = global::Mono.Unix.Catalog.GetString("5. sat");
			this.hbox25.Add(this.button114_);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.button114_]));
			w97.Position = 2;
			w97.Expand = false;
			w97.Fill = false;
			this.vbox10.Add(this.hbox25);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox25]));
			w98.Position = 0;
			w98.Expand = false;
			w98.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.button120_ = new global::Gtk.Button();
			this.button120_.WidthRequest = 100;
			this.button120_.CanFocus = true;
			this.button120_.Name = "button120_";
			this.button120_.UseUnderline = true;
			this.button120_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox27.Add(this.button120_);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.button120_]));
			w99.Position = 0;
			w99.Expand = false;
			w99.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.button121_ = new global::Gtk.Button();
			this.button121_.WidthRequest = 100;
			this.button121_.CanFocus = true;
			this.button121_.Name = "button121_";
			this.button121_.UseUnderline = true;
			this.button121_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox28.Add(this.button121_);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.button121_]));
			w100.Position = 0;
			w100.Expand = false;
			w100.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.button122_ = new global::Gtk.Button();
			this.button122_.WidthRequest = 100;
			this.button122_.CanFocus = true;
			this.button122_.Name = "button122_";
			this.button122_.UseUnderline = true;
			this.button122_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox28.Add(this.button122_);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.button122_]));
			w101.Position = 1;
			w101.Expand = false;
			w101.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.button123_ = new global::Gtk.Button();
			this.button123_.WidthRequest = 100;
			this.button123_.CanFocus = true;
			this.button123_.Name = "button123_";
			this.button123_.UseUnderline = true;
			this.button123_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox28.Add(this.button123_);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.button123_]));
			w102.Position = 2;
			w102.Expand = false;
			w102.Fill = false;
			this.hbox27.Add(this.hbox28);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.hbox28]));
			w103.Position = 1;
			w103.Expand = false;
			w103.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.button124_ = new global::Gtk.Button();
			this.button124_.WidthRequest = 100;
			this.button124_.CanFocus = true;
			this.button124_.Name = "button124_";
			this.button124_.UseUnderline = true;
			this.button124_.Label = global::Mono.Unix.Catalog.GetString("6. sat");
			this.hbox27.Add(this.button124_);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.button124_]));
			w104.Position = 2;
			w104.Expand = false;
			w104.Fill = false;
			this.vbox10.Add(this.hbox27);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox27]));
			w105.Position = 1;
			w105.Expand = false;
			w105.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox29 = new global::Gtk.HBox();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.button130_ = new global::Gtk.Button();
			this.button130_.WidthRequest = 100;
			this.button130_.CanFocus = true;
			this.button130_.Name = "button130_";
			this.button130_.UseUnderline = true;
			this.button130_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox29.Add(this.button130_);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.button130_]));
			w106.Position = 0;
			w106.Expand = false;
			w106.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.hbox30 = new global::Gtk.HBox();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.button131_ = new global::Gtk.Button();
			this.button131_.WidthRequest = 100;
			this.button131_.CanFocus = true;
			this.button131_.Name = "button131_";
			this.button131_.UseUnderline = true;
			this.button131_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox30.Add(this.button131_);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.button131_]));
			w107.Position = 0;
			w107.Expand = false;
			w107.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.button132_ = new global::Gtk.Button();
			this.button132_.WidthRequest = 100;
			this.button132_.CanFocus = true;
			this.button132_.Name = "button132_";
			this.button132_.UseUnderline = true;
			this.button132_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox30.Add(this.button132_);
			global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.button132_]));
			w108.Position = 1;
			w108.Expand = false;
			w108.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.button133_ = new global::Gtk.Button();
			this.button133_.WidthRequest = 100;
			this.button133_.CanFocus = true;
			this.button133_.Name = "button133_";
			this.button133_.UseUnderline = true;
			this.button133_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox30.Add(this.button133_);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.button133_]));
			w109.Position = 2;
			w109.Expand = false;
			w109.Fill = false;
			this.hbox29.Add(this.hbox30);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.hbox30]));
			w110.Position = 1;
			w110.Expand = false;
			w110.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.button134_ = new global::Gtk.Button();
			this.button134_.WidthRequest = 100;
			this.button134_.CanFocus = true;
			this.button134_.Name = "button134_";
			this.button134_.UseUnderline = true;
			this.button134_.Label = global::Mono.Unix.Catalog.GetString("7. sat");
			this.hbox29.Add(this.button134_);
			global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.button134_]));
			w111.Position = 2;
			w111.Expand = false;
			w111.Fill = false;
			this.vbox10.Add(this.hbox29);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox29]));
			w112.Position = 2;
			w112.Expand = false;
			w112.Fill = false;
			this.vbox5.Add(this.vbox10);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox10]));
			w113.Position = 1;
			w113.Expand = false;
			w113.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.button140_ = new global::Gtk.Button();
			this.button140_.WidthRequest = 100;
			this.button140_.CanFocus = true;
			this.button140_.Name = "button140_";
			this.button140_.UseUnderline = true;
			this.button140_.Label = global::Mono.Unix.Catalog.GetString("8. sat");
			this.hbox31.Add(this.button140_);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.button140_]));
			w114.Position = 0;
			w114.Expand = false;
			w114.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.hbox32 = new global::Gtk.HBox();
			this.hbox32.Name = "hbox32";
			this.hbox32.Spacing = 6;
			// Container child hbox32.Gtk.Box+BoxChild
			this.button141_ = new global::Gtk.Button();
			this.button141_.WidthRequest = 100;
			this.button141_.CanFocus = true;
			this.button141_.Name = "button141_";
			this.button141_.UseUnderline = true;
			this.button141_.Label = global::Mono.Unix.Catalog.GetString("8. sat");
			this.hbox32.Add(this.button141_);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.button141_]));
			w115.Position = 0;
			w115.Expand = false;
			w115.Fill = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.button142_ = new global::Gtk.Button();
			this.button142_.WidthRequest = 100;
			this.button142_.CanFocus = true;
			this.button142_.Name = "button142_";
			this.button142_.UseUnderline = true;
			this.button142_.Label = global::Mono.Unix.Catalog.GetString("8. sat");
			this.hbox32.Add(this.button142_);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.button142_]));
			w116.Position = 1;
			w116.Expand = false;
			w116.Fill = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.button143_ = new global::Gtk.Button();
			this.button143_.WidthRequest = 100;
			this.button143_.CanFocus = true;
			this.button143_.Name = "button143_";
			this.button143_.UseUnderline = true;
			this.button143_.Label = global::Mono.Unix.Catalog.GetString("8. sat");
			this.hbox32.Add(this.button143_);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.button143_]));
			w117.Position = 2;
			w117.Expand = false;
			w117.Fill = false;
			this.hbox31.Add(this.hbox32);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.hbox32]));
			w118.Position = 1;
			w118.Expand = false;
			w118.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.button144_ = new global::Gtk.Button();
			this.button144_.WidthRequest = 100;
			this.button144_.CanFocus = true;
			this.button144_.Name = "button144_";
			this.button144_.UseUnderline = true;
			this.button144_.Label = global::Mono.Unix.Catalog.GetString("8. sat");
			this.hbox31.Add(this.button144_);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.button144_]));
			w119.Position = 2;
			w119.Expand = false;
			w119.Fill = false;
			this.vbox9.Add(this.hbox31);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox31]));
			w120.Position = 0;
			w120.Expand = false;
			w120.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox33 = new global::Gtk.HBox();
			this.hbox33.Name = "hbox33";
			this.hbox33.Homogeneous = true;
			this.hbox33.Spacing = -151;
			// Container child hbox33.Gtk.Box+BoxChild
			this.button_spremi = new global::Gtk.Button();
			this.button_spremi.WidthRequest = 100;
			this.button_spremi.CanFocus = true;
			this.button_spremi.Name = "button_spremi";
			this.button_spremi.UseUnderline = true;
			this.button_spremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.hbox33.Add(this.button_spremi);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.button_spremi]));
			w121.Position = 0;
			w121.Expand = false;
			w121.Fill = false;
			// Container child hbox33.Gtk.Box+BoxChild
			this.button_odustani = new global::Gtk.Button();
			this.button_odustani.WidthRequest = 100;
			this.button_odustani.CanFocus = true;
			this.button_odustani.Name = "button_odustani";
			this.button_odustani.UseUnderline = true;
			this.button_odustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox33.Add(this.button_odustani);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.button_odustani]));
			w122.Position = 1;
			w122.Expand = false;
			w122.Fill = false;
			this.vbox9.Add(this.hbox33);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox33]));
			w123.Position = 1;
			w123.Expand = false;
			w123.Fill = false;
			w123.Padding = ((uint)(15));
			this.vbox5.Add(this.vbox9);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox9]));
			w124.Position = 2;
			w124.Expand = false;
			w124.Fill = false;
			this.vbox2.Add(this.vbox5);
			global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox5]));
			w125.Position = 1;
			w125.Expand = false;
			w125.Fill = false;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w126.Position = 2;
			w126.Expand = false;
			w126.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 612;
			this.DefaultHeight = 800;
			this.Show();
			this.button00_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button01_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button02_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button03_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button04_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button10_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button11_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button12_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button13_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button14_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button20_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button21_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button22_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button23_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button24_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button30_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button31_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button32_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button33_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button34_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button40_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button41_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button42_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button43_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button44_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button50_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button51_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button52_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button53_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button54_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button60_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button61_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button62_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button63_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button64_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button70_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button71_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button72_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button73_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button74_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button80_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button81_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button82_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button83_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button84_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button90_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button91_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button92_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button93_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button94_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button100_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button101_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button102_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button103_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button104_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button110_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button111_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button112_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button113_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button114_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button120_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button121_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button122_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button123_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button124_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button130_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button131_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button132_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button133_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button134_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button140_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button141_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button142_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button143_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button144_.Clicked += new global::System.EventHandler(this.OnButtonClicked);
			this.button_spremi.Clicked += new global::System.EventHandler(this.OnButtonSpremiClicked);
			this.button_odustani.Clicked += new global::System.EventHandler(this.OnButtonOdustaniClicked);
		}
	}
}
