
// This file has been generated by the GUI designer. Do not modify.
namespace Raspored
{
	public partial class DodajPredavacaWindow
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label5;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label6;

		private global::Gtk.Entry entry_ime;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label7;

		private global::Gtk.Entry entry_prezime;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label8;

		private global::Gtk.Entry entry_adresa;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label9;

		private global::Gtk.Entry entry_OIB;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Button button_Spremi;

		private global::Gtk.Button button_odustani;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Raspored.DodajPredavacaWindow
			this.WidthRequest = 380;
			this.HeightRequest = 230;
			this.Name = "Raspored.DodajPredavacaWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Dodaj predavaca");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("Raspored.Logo_smanjeni.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.BorderWidth = ((uint)(20));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Raspored.DodajPredavacaWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Unesite podatke:");
			this.vbox4.Add(this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label5]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 1;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Ime:");
			this.hbox5.Add(this.label6);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label6]));
			w2.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entry_ime = new global::Gtk.Entry();
			this.entry_ime.CanFocus = true;
			this.entry_ime.Name = "entry_ime";
			this.entry_ime.IsEditable = true;
			this.entry_ime.InvisibleChar = '●';
			this.hbox5.Add(this.entry_ime);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry_ime]));
			w3.Position = 1;
			this.vbox5.Add(this.hbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 1;
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Prezime:");
			this.hbox6.Add(this.label7);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label7]));
			w5.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entry_prezime = new global::Gtk.Entry();
			this.entry_prezime.CanFocus = true;
			this.entry_prezime.Name = "entry_prezime";
			this.entry_prezime.IsEditable = true;
			this.entry_prezime.InvisibleChar = '●';
			this.hbox6.Add(this.entry_prezime);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entry_prezime]));
			w6.Position = 1;
			this.vbox5.Add(this.hbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 1;
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Adresa:");
			this.hbox7.Add(this.label8);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label8]));
			w8.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry_adresa = new global::Gtk.Entry();
			this.entry_adresa.CanFocus = true;
			this.entry_adresa.Name = "entry_adresa";
			this.entry_adresa.IsEditable = true;
			this.entry_adresa.InvisibleChar = '●';
			this.hbox7.Add(this.entry_adresa);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry_adresa]));
			w9.Position = 1;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox4.Add(this.vbox5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox5]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.WidthRequest = 1;
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("OIB:");
			this.hbox8.Add(this.label9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label9]));
			w12.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entry_OIB = new global::Gtk.Entry();
			this.entry_OIB.CanFocus = true;
			this.entry_OIB.Name = "entry_OIB";
			this.entry_OIB.IsEditable = true;
			this.entry_OIB.InvisibleChar = '●';
			this.hbox8.Add(this.entry_OIB);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.entry_OIB]));
			w13.Position = 1;
			this.vbox6.Add(this.hbox8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox8]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.WidthRequest = 0;
			this.hbox9.Name = "hbox9";
			this.hbox9.Homogeneous = true;
			this.hbox9.Spacing = -100;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button_Spremi = new global::Gtk.Button();
			this.button_Spremi.WidthRequest = 100;
			this.button_Spremi.CanFocus = true;
			this.button_Spremi.Name = "button_Spremi";
			this.button_Spremi.UseUnderline = true;
			this.button_Spremi.Label = global::Mono.Unix.Catalog.GetString("Spremi");
			this.hbox9.Add(this.button_Spremi);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button_Spremi]));
			w15.Position = 0;
			w15.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button_odustani = new global::Gtk.Button();
			this.button_odustani.WidthRequest = 100;
			this.button_odustani.CanFocus = true;
			this.button_odustani.Name = "button_odustani";
			this.button_odustani.UseUnderline = true;
			this.button_odustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox9.Add(this.button_odustani);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button_odustani]));
			w16.Position = 1;
			w16.Fill = false;
			this.vbox6.Add(this.hbox9);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
			w17.Position = 1;
			w17.Fill = false;
			w17.Padding = ((uint)(10));
			this.vbox4.Add(this.vbox6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox6]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 393;
			this.DefaultHeight = 280;
			this.Show();
			this.button_Spremi.Clicked += new global::System.EventHandler(this.OnButtonSpremiClicked);
			this.button_odustani.Clicked += new global::System.EventHandler(this.OnButtonOdustaniClicked);
		}
	}
}
