
// This file has been generated by the GUI designer. Do not modify.
namespace Raspored
{
	public partial class PregledajUcioneWindow
	{
		private global::Gtk.VBox vbox8;

		private global::Gtk.Label label10;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview_Ucionica;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Button button_natrag;

		private global::Gtk.Button button_izbrisiUcionicu;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Raspored.PregledajUcioneWindow
			this.Name = "Raspored.PregledajUcioneWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("PregledajUcioneWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.BorderWidth = ((uint)(20));
			// Container child Raspored.PregledajUcioneWindow.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Prikaz učionica:");
			this.vbox8.Add(this.label10);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label10]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview_Ucionica = new global::Gtk.NodeView();
			this.nodeview_Ucionica.CanFocus = true;
			this.nodeview_Ucionica.Name = "nodeview_Ucionica";
			this.GtkScrolledWindow.Add(this.nodeview_Ucionica);
			this.vbox8.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Homogeneous = true;
			this.hbox10.Spacing = 330;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button_natrag = new global::Gtk.Button();
			this.button_natrag.WidthRequest = 100;
			this.button_natrag.CanFocus = true;
			this.button_natrag.Name = "button_natrag";
			this.button_natrag.UseUnderline = true;
			this.button_natrag.Label = global::Mono.Unix.Catalog.GetString("Natrag");
			this.hbox10.Add(this.button_natrag);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button_natrag]));
			w4.Position = 0;
			w4.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button_izbrisiUcionicu = new global::Gtk.Button();
			this.button_izbrisiUcionicu.WidthRequest = 100;
			this.button_izbrisiUcionicu.CanFocus = true;
			this.button_izbrisiUcionicu.Name = "button_izbrisiUcionicu";
			this.button_izbrisiUcionicu.UseUnderline = true;
			this.button_izbrisiUcionicu.Label = global::Mono.Unix.Catalog.GetString("Izbriši učionicu");
			this.hbox10.Add(this.button_izbrisiUcionicu);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.button_izbrisiUcionicu]));
			w5.Position = 1;
			w5.Fill = false;
			this.vbox8.Add(this.hbox10);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox10]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(10));
			this.Add(this.vbox8);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 585;
			this.DefaultHeight = 388;
			this.Show();
			this.button_natrag.Clicked += new global::System.EventHandler(this.OnButtonNatragClicked);
			this.button_izbrisiUcionicu.Clicked += new global::System.EventHandler(this.OnButtonIzbrisiUcionicuClicked);
		}
	}
}
