
// This file has been generated by the GUI designer. Do not modify.
namespace Raspored
{
	public partial class PregledajPredavacaWindow
	{
		private global::Gtk.VBox vbox9;

		private global::Gtk.Label label11;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview_predavaci;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Button button_natrag;

		private global::Gtk.Button button_izbrisiPredavaca;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Raspored.PregledajPredavacaWindow
			this.Name = "Raspored.PregledajPredavacaWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("PregledajPredavacaWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(20));
			// Container child Raspored.PregledajPredavacaWindow.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Prikaz predavača:");
			this.vbox9.Add(this.label11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview_predavaci = new global::Gtk.NodeView();
			this.nodeview_predavaci.CanFocus = true;
			this.nodeview_predavaci.Name = "nodeview_predavaci";
			this.GtkScrolledWindow.Add(this.nodeview_predavaci);
			this.vbox9.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Homogeneous = true;
			this.hbox11.Spacing = 330;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button_natrag = new global::Gtk.Button();
			this.button_natrag.WidthRequest = 100;
			this.button_natrag.CanFocus = true;
			this.button_natrag.Name = "button_natrag";
			this.button_natrag.UseUnderline = true;
			this.button_natrag.Label = global::Mono.Unix.Catalog.GetString("Natrag");
			this.hbox11.Add(this.button_natrag);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button_natrag]));
			w4.Position = 0;
			w4.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button_izbrisiPredavaca = new global::Gtk.Button();
			this.button_izbrisiPredavaca.WidthRequest = 100;
			this.button_izbrisiPredavaca.CanFocus = true;
			this.button_izbrisiPredavaca.Name = "button_izbrisiPredavaca";
			this.button_izbrisiPredavaca.UseUnderline = true;
			this.button_izbrisiPredavaca.Label = global::Mono.Unix.Catalog.GetString("Izbriši predavača");
			this.hbox11.Add(this.button_izbrisiPredavaca);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button_izbrisiPredavaca]));
			w5.Position = 1;
			w5.Fill = false;
			this.vbox9.Add(this.hbox11);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox11]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(10));
			this.Add(this.vbox9);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 598;
			this.DefaultHeight = 353;
			this.Show();
			this.button_natrag.Clicked += new global::System.EventHandler(this.OnButtonNatragClicked);
			this.button_izbrisiPredavaca.Clicked += new global::System.EventHandler(this.OnButtonIzbrisiPredavacaClicked);
		}
	}
}
