
// This file has been generated by the GUI designer. Do not modify.
namespace Raspored
{
	public partial class ZauzmiUcionuWindow
	{
		private global::Gtk.VBox vbox10;

		private global::Gtk.Label label12;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview_odabirUcionice;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Label label13;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.NodeView nodeview_odabirPredavaca;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button button_odustani;

		private global::Gtk.Button button_dalje;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Raspored.ZauzmiUcionuWindow
			this.Name = "Raspored.ZauzmiUcionuWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Zauzmi Učionu");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.BorderWidth = ((uint)(10));
			// Container child Raspored.ZauzmiUcionuWindow.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Odaberi učionicu:");
			this.vbox10.Add(this.label12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label12]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview_odabirUcionice = new global::Gtk.NodeView();
			this.nodeview_odabirUcionice.CanFocus = true;
			this.nodeview_odabirUcionice.Name = "nodeview_odabirUcionice";
			this.GtkScrolledWindow.Add(this.nodeview_odabirUcionice);
			this.vbox10.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Odaberi predavača:");
			this.vbox11.Add(this.label13);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label13]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.nodeview_odabirPredavaca = new global::Gtk.NodeView();
			this.nodeview_odabirPredavaca.CanFocus = true;
			this.nodeview_odabirPredavaca.Name = "nodeview_odabirPredavaca";
			this.GtkScrolledWindow1.Add(this.nodeview_odabirPredavaca);
			this.vbox11.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.GtkScrolledWindow1]));
			w6.Position = 1;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Homogeneous = true;
			this.hbox12.Spacing = 330;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button_odustani = new global::Gtk.Button();
			this.button_odustani.WidthRequest = 100;
			this.button_odustani.CanFocus = true;
			this.button_odustani.Name = "button_odustani";
			this.button_odustani.UseUnderline = true;
			this.button_odustani.Label = global::Mono.Unix.Catalog.GetString("Odustani");
			this.hbox12.Add(this.button_odustani);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button_odustani]));
			w7.Position = 0;
			w7.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button_dalje = new global::Gtk.Button();
			this.button_dalje.WidthRequest = 100;
			this.button_dalje.CanFocus = true;
			this.button_dalje.Name = "button_dalje";
			this.button_dalje.UseUnderline = true;
			this.button_dalje.Label = global::Mono.Unix.Catalog.GetString("Dalje");
			this.hbox12.Add(this.button_dalje);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button_dalje]));
			w8.Position = 1;
			w8.Fill = false;
			this.vbox11.Add(this.hbox12);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox12]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox10.Add(this.vbox11);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.vbox11]));
			w10.Position = 2;
			this.Add(this.vbox10);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 598;
			this.DefaultHeight = 428;
			this.Show();
			this.button_odustani.Clicked += new global::System.EventHandler(this.OnButtonOdustaniClicked);
			this.button_dalje.Clicked += new global::System.EventHandler(this.OnButtonDaljeClicked);
		}
	}
}
